export const CLIENT_ADD_REQUEST = "CLIENT_ADD_REQUEST";
export const CLIENT_ADD_SUCCESS = "CLIENT_ADD_SUCCESS";
export const CLIENT_LOGIN_FAIL = "CLIENT_LOGIN_FAIL";
export const CLIENT_GET_REQUEST = "CLIENT_GET_REQUEST";
export const CLIENT_FETCH_SUCCESS = "CLIENT_FETCH_SUCCESS";
export const CLIENT_FETCH_FAILED = "CLIENT_FETCH_FAILED";
