export const FOLDER_ADD_REQUEST = "FOLDER_ADD_REQUEST";
export const FOLDER_ADD_SUCCESS = "FOLDER_ADD_SUCCESS";
export const FOLDER_LOGIN_FAIL = "FOLDER_LOGIN_FAIL";
export const FOLDER_GET_REQUEST = "FOLDER_GET_REQUEST";
export const FOLDER_FETCH_SUCCESS = "FOLDER_FETCH_SUCCESS";
export const FOLDER_FETCH_FAILED = "FOLDER_FETCH_FAILED";