export const IMAGE_ADD_REQUEST = "IMAGE_ADD_REQUEST";
export const IMAGE_ADD_SUCCESS = "IMAGE_ADD_SUCCESS";
export const IMAGE_LOGIN_FAIL = "IMAGE_LOGIN_FAIL";
export const IMAGE_GET_REQUEST = "IMAGE_GET_REQUEST";
export const IMAGE_FETCH_SUCCESS = "IMAGE_FETCH_SUCCESS";
export const IMAGE_FETCH_FAILED = "IMAGE_FETCH_FAILED";